### ISSUE TITLE
selenium-webdriver support broken in firefox 47

### ISSUE THREAD

**Issue by dylan-okeefe** [learn-co-students/using-active-model-serializer-lab-v-000#55]
If a student is having trouble with the test and getting error messages with the selenium-webdriver gem, be aware that support was broken with firefox 47, released June 7th, 2016. Replicated the issue on my local environment, downgrading to firefox 46 fixed the issue.

**Comment by zacscodingclub** [comment]
I couldn't be bothered to download firefox, so I found a way around this by setting the the driver to use Chrome using this bit of code in the `rails_helper.rb`

```
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
```

**Comment by Dom-Mc** [comment]
With so many labs depending on Selenium, this issue really should be noted. Plus given how far back this issue dates, there doesn't appear to be a solution in the near future.

The following recommendation got rid of the timeout error:
```
#Gemfile
group :development, :test do
  gem 'poltergeist'
end

#spec_helper.rb
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist
```
